# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MagiApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MagiApp

  # 网络库
  pod 'Alamofire', '~> 4.7'
  pod 'Moya', '~> 11.0'

  # 信号
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  # 图片缓存
  pod 'Kingfisher’
  # 字典转模型
  pod 'ObjectMapper'
  # 约束 autolayout
  pod 'SnapKit'
  # 传输协议
  pod 'SwiftProtobuf'
  # 图表绘制
  pod 'Charts'
  # 异步绘制框架
  pod "Texture"

  target 'MagiAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
  end

  target 'MagiAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
