# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MagiApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MagiApp

  # 网络库
  pod 'Alamofire', '~> 4.7' ,:inhibit_warnings => true
  pod 'Moya', '~> 11.0' ,:inhibit_warnings => true

  # 信号
  pod 'RxSwift',    '~> 4.0' ,:inhibit_warnings => true
  pod 'RxCocoa',    '~> 4.0' ,:inhibit_warnings => true
  # 图片缓存
  pod 'Kingfisher’ ,:inhibit_warnings => true
  # 字典转模型
  pod 'ObjectMapper' ,:inhibit_warnings => true
  # 约束 autolayout ,:inhibit_warnings => true
  pod 'SnapKit' ,:inhibit_warnings => true
  # 传输协议
  pod 'SwiftProtobuf' ,:inhibit_warnings => true
  # 图表绘制
  pod 'Charts' ,:inhibit_warnings => true
  # 异步绘制框架
  pod "Texture" ,:inhibit_warnings => true

  target 'MagiAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
  end

  target 'MagiAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
